### PR TITLE
[PATCH] Fix bug where Employee model not linked to business.

### LINKED ISSUE #82: [BUG] Employee model not linked to business
Description: Employee model not linked to business

image

Missing array of EmployeeAccount
image

Missing belongto business link
image

### PR DESCRIPTION
**Pull request by nasaku898**
Commit number in commit is wrong. Instead of 86 it should be 82.
closes #82

### CODE REVIEW

**Review by Mnx458 — DISMISSED** [review]
Good

File: frontend/src/components/CreateEmployee/CreateEmployee.tsx [hunk 1]
```diff
@@ -44,6 +50,8 @@ const CreateEmployee: React.FC = () => {
       country: '',
       title: '',
       hourlyWage: '',
+      businessId: '',
+      isAdmin: account.admin ? account.admin : false,
```
Comment (Manraj45) [inline frontend/src/components/CreateEmployee/CreateEmployee.tsx:54]: Wouldn't it be better here to just put "isAdmin: account.admin"? Since if it's true then it will be true and if it's false it will be false.

File: frontend/src/features/account/AccountSlice.tsx [hunk 2]
```diff
@@ -65,6 +65,7 @@ export const AccountSlice = createSlice({
       })
       .addCase(getAccount.fulfilled, (state, action) => {
         if (action.payload.account) {
+          state.loading = false;
```
Comment (Manraj45) [inline frontend/src/features/account/AccountSlice.tsx:68]: Shouldn't this be at the end?

**Review by Manraj45 — CHANGES_REQUESTED** [review]
Great job! I had a few questions for some parts that you can look at.

File: frontend/src/components/CreateEmployee/CreateEmployee.tsx (hunk 1 above)
Comment (nasaku898) [reply frontend/src/components/CreateEmployee/CreateEmployee.tsx:54]: The reason I did this is because the return value from the backend can be an empty string. I want `isAdmin` to be an actual Boolean in the frontend.

File: frontend/src/features/account/AccountSlice.tsx (hunk 2 above)
Comment (nasaku898) [reply frontend/src/features/account/AccountSlice.tsx]: Good catch.

**Review by Manraj45 — APPROVED** [review]
Good job!

**Review by Mnx458 — APPROVED** [review]
