### PR TITLE
[MINOR] Fixed bug where get and get all accounts would retrieve the password.

### LINKED ISSUE #73: [BUG] Retrieving account also retrieve their password
Description: When requesting an account from the backend, the endpoint return the full entity. We should return a dto instead and hide sensitive information such as the password.

### PR DESCRIPTION
**Pull request by nasaku898**
- Change get request such that it returns a DTO without the password. 
closes #73

### CODE REVIEW

File: backend/src/main/routes/AccountRoute.ts [hunk 1]
```diff
@@ -62,7 +77,10 @@ export default class AccountRoute extends CommonRoutesConfig {
       .get(async (req: express.Request, res: express.Response, next: express.NextFunction) => {
         try {
           const employeeAccount = await this.employeeAccountService.getEmployeeAccountByEmail(req.params.email);
-          res.status(StatusCodes.OK).send(employeeAccount);
+          console.log(employeeAccount);
```
Comment (huangs08) [inline backend/src/main/routes/AccountRoute.ts:80]: Remove console.log

**Review by davidthai0387 — APPROVED** [review]

File: backend/src/main/routes/AccountRoute.ts (hunk 1 above)
Comment (nasaku898) [reply backend/src/main/routes/AccountRoute.ts]: good catch, it's removed

**Review by huangs08 — APPROVED** [review]

**Review by kevin-ghannoum — APPROVED** [review]
