### PR TITLE
[PATCH] Fixed bugs of the sidebar and of the role authentification and styling consistency.

### LINKED ISSUE #250: [Bug] The users can see all the items in the menu regardless of their role
### Steps to reproduce

1. Log to the app using a role other than admin (because that role has access to all the pages)
2. Visit a page like the logs page (/logs)
3. Open the menu on the side

### Expected results

The expected result is that the user will only see in the menu the items they are allowed to access.

### Actual results

The users can see all the items in the menu regardless of their role. However, upon selecting an item for which they do not have the role, they are redirected to the root page.

### Screenshots

_No response_

### Relevant log output

_No response_

### Severity

Medium

### LINKED ISSUE #269: [Bug] Employee account shows role of business in redux state
### Steps to reproduce

- login as an employee
- look at redux state of account
- it will have wrong role. It is hard coded as business

### Expected results

Expect employee to have role of employee, not business.

### Actual results

Currently employee account shows as business role.

### Screenshots

image

### Relevant log output

```shell
No log
```

### Severity

High

### PR DESCRIPTION
**Pull request by jmezaber**
Closes #250, closes #269 

## Sidebar bug fix
Sidebar - Admin
Screen Shot 2022-03-30 at 6 33 21 PM

Sidebar - Employee
Screen Shot 2022-03-30 at 6 41 46 PM

## Role authentification bug fix
Screen Shot 2022-03-30 at 6 41 08 PM

## Style consistency

For style consistency, I made sure that all the pages could first be visited and the flow of the pages was valid. Then I made sure that all the pages had a similar styling, from button placement to paper placement.

### CODE REVIEW

File: frontend/src/components/Project/ViewProject.tsx [hunk 1]
```diff
@@ -212,15 +212,19 @@ const ViewProject: React.FC = () => {
           <Grid item xs={4}></Grid>
           <Grid item xs={4}></Grid>
           <Grid item xs={4}>
```
Comment (nasaku898) [inline frontend/src/components/Project/ViewProject.tsx:214]: You can conditionally rendered the grid instead of showing an empty one.

**Review by Manraj45 — APPROVED** [review]
Good Job!
