### PR TITLE
[MINOR] Fixed bug where website, social media name and link were required.

### LINKED ISSUE #74: [BUG] Social media information is currently a required field but it should not according to the requirement
Description: Social media information is currently a required field but it should not according to the requirement. Should change such that if there is not social media information. Don't attempt to create the entity in db,
image

### PR DESCRIPTION
**Pull request by nasaku898**
- Made webiste, social media name and link optional
- Updated test to reflect new logic
- fix bug where migration of `20211018051500-create-employee-hours-input-type` was not working
closes #74

### CODE REVIEW

File: frontend/src/services/AccountAPI.ts [hunk 1]
```diff
@@ -14,12 +14,26 @@ export const createEmployeeAccount = async (
 export const createBusinessAccount = async (
   businessAccountRequestDTO: BusinessCreationRequestDTO
 ): Promise<AxiosResponse<any>> => {
+  if (
+    !businessAccountRequestDTO.socialMediaInfo ||
+    !businessAccountRequestDTO.socialMediaInfo.link ||
+    !businessAccountRequestDTO.socialMediaInfo.link
```
Comment (davidthai0387) [inline frontend/src/services/AccountAPI.ts:20]: duplicate conditions?

File: frontend/src/services/AccountAPI.ts [hunk 2]
```diff
@@ -14,12 +14,26 @@ export const createEmployeeAccount = async (
...
   return axios.post(`/accounts/business`, businessAccountRequestDTO);
 };
 
 export const createClientAccount = async (
   clientAccountCreationRequestDTO: ClientAccountCreationRequestDTO
 ): Promise<AxiosResponse<any>> => {
+  if (
+    !clientAccountCreationRequestDTO.socialMediaInfo ||
+    !clientAccountCreationRequestDTO.socialMediaInfo.link ||
+    !clientAccountCreationRequestDTO.socialMediaInfo.link
```
Comment (davidthai0387) [inline frontend/src/services/AccountAPI.ts:33]: same thing here

**Review by davidthai0387 — DISMISSED** [review]
few comments, looks good otherwise

File: frontend/src/services/AccountAPI.ts (hunk 2 above)
Comment (nasaku898) [reply frontend/src/services/AccountAPI.ts]: Nice catch, it's removed.

File: frontend/src/services/AccountAPI.ts (hunk 1 above)
Comment (nasaku898) [reply frontend/src/services/AccountAPI.ts]: good catch, it's removed!

**Review by Manraj45 — APPROVED** [review]

**Review by jmezaber — APPROVED** [review]
Looks good!

**Review by kevin-ghannoum — APPROVED** [review]
