### PR TITLE
[PATCH] Fixed code smells.

### LINKED ISSUE #138: Redundant use of `await` on a return value.
An async function always wraps the return value in a Promise. Using return await is therefore redundant.

backend/src/main/services/TaskService.ts (20)
backend/src/main/services/UserService.ts (17, 21)

Solution: Remove await.

### LINKED ISSUE #139: Rename files or classes.
By convention, a file that exports only one class, function, or constant should be named for that class, function or constant. Anything else may confuse maintainers.

backend/src/main/repositories/TransactionRepopsitory.ts
frontend/src/components/CreateBusinessAccount/CreateBusinessAccountStyle.ts
frontend/src/components/CreateBusinessAccount/CreateBusinessFormValidationSchema.ts
frontend/src/components/CreateClientAccount/CreateClientAccountStyle.tsx
frontend/src/components/CreateClientAccount/CreateClientFormValidationSchema.ts
frontend/src/components/CreateEmployee/CreateEmployeeFormValidationSchema.ts
frontend/src/components/CreateEmployee/CreateEmployeeStyle.ts
frontend/src/components/LogHours/LogHoursFormValidationSchema.ts
frontend/src/components/LogHours/LogHoursStyle.ts
frontend/src/components/Login/LoginFormValidationSchema.ts
frontend/src/components/Login/LoginStyle.ts
frontend/src/components/Project/CreateProjectFormValidationSchema.ts
frontend/src/components/Project/CreateProjectStyle.ts
frontend/src/components/Sidebar/SidebarStyle.ts
frontend/src/components/Task/CreateTask.tsx
frontend/src/components/Task/CreateTaskFormValidation.ts
frontend/src/components/Task/TaskStyle.ts

### LINKED ISSUE #140: Use concise character class syntax '\d' instead of '[0-9]'.
With regular expressions syntax, it’s possible to express the same thing in many ways. For example, to match a two-digit number, one could write [0-9]{2,2} or \d{2}. Latter is not only shorter in terms of expression length, but also easier to read and thus to maintain. This rule recommends to replace some bulky quantifiers and character classes with more concise equivalents:

\d for [0-9] and \D for [^0-9]
\w for [A-Za-z0-9_] and \W for [^A-Za-z0-9_]
. for character classes matching everything (e.g. [\w\W], [\d\D], or [\s\S] with s flag)
x? for x{0,1}, x* for x{0,}, x+ for x{1,}, x{N} for x{N,N}

frontend/src/serviceWorker.ts (18)

### LINKED ISSUE #141: Fix imports.
Multiple imports from the same module should be merged together to improve readability.
backend/src/main/app.ts (11, 12)

Import is duplicated.
frontend/src/App.tsx (8)

Remove unused import.
frontend/src/App.test.tsx

### LINKED ISSUE #142: Replace this "String" wrapper object with primitive type "string".
The use of wrapper objects for primitive types is gratuitous, confusing and dangerous. If you use a wrapper object constructor for type conversion, just remove the new keyword, and you’ll get a primitive value automatically. If you use a wrapper object as a way to add properties to a primitive, you should re-think the design. Such uses are considered bad practice, and should be refactored.

frontend/src/services/LogHoursAPI.ts (8, 12)

### LINKED ISSUE #143: Rename interface to match the regular expression ^[A-Z][a-zA-Z0-9]*$.
Shared coding conventions allow teams to collaborate effectively. This rule allows to check that all class names (and interfaces for TypeScript) match a provided regular expression.

frontend/src/components/Login/Login.tsx (11)
frontend/src/components/Project/CreateProject.tsx (28)

### LINKED ISSUE #144: Variable is already declared in the upper scope.
Overriding or shadowing a variable declared in an outer scope can strongly impact the readability, and therefore the maintainability, of a piece of code. Further, it could lead maintainers to introduce bugs because they think they’re using one variable but are really using another.

backend/src/main/services/ProjectService.ts (87)
frontend/src/components/LogHours/LogHours.tsx (86)
frontend/src/components/Project/CreateProject.tsx (124, 171)

### PR DESCRIPTION
**Pull request by kevin-ghannoum**
closes #138
closes #139 
closes #140
closes #141
closes #142
closes #143
closes #144

### CODE REVIEW

File: backend/src/main/services/TaskService.ts [hunk 1]
```diff
@@ -17,7 +17,7 @@ export class TaskService {
     if (TaskService.isThereNullValueTaskCreationDTO(taskDTO)) {
       throw new HttpException(StatusCodes.BAD_REQUEST, 'Request data is missing some values');
     }
-    return await this.taskRepository.create(taskDTO);
+    return this.taskRepository.create(taskDTO);
```
Comment (Manraj45) [inline backend/src/main/services/TaskService.ts:20]: Did you try running it? Does it break the code when you remove the await?

File: frontend/src/App.test.tsx [hunk 2]
```diff
@@ -1,9 +1,5 @@
-import React from 'react';
-import { render } from '@testing-library/react';
-import { Provider } from 'react-redux';
-import { store } from './redux/store';
-import App from './App';
-
 test('initial test to test the framework', () => {
```
Comment (Manraj45) [inline frontend/src/App.test.tsx:1]: You can remove this file since it was created to test the testing framework.

**Review by Manraj45 — CHANGES_REQUESTED** [review]
Seems good. Make sure that everything is running correctly. I also left a few comments.

File: backend/src/main/services/TaskService.ts (hunk 1 above)
Comment (nasaku898) [reply backend/src/main/services/TaskService.ts:20]: This shouldn't break it. Since it return a promise. And for other services, we return it this way.

File: frontend/src/App.test.tsx (hunk 2 above)
Comment (nasaku898) [reply frontend/src/App.test.tsx:1]: I think we should keep it for now because it's the only unit test we have in the frontend. Without a least 1 unit test, I think the test command would break. But we should add more tests soon.

**Review by nasaku898 — APPROVED** [review]
Looks good, I like the refactoring you did. Our metrics should improve significantly!

**Review by Manraj45 — DISMISSED** [review]
Good job!

**Review by Mnx458 — APPROVED** [review]
Good job on the code smells

**Review by nasaku898 — APPROVED** [review]
